{
  "name": "Bitfocus Companion",
  "version": "1.0.0",
  "slug": "bitfocus_companion",
  "description": "Home Assistant add-on voor het draaien van Bitfocus Companion.",
  "startup": "services",
  "boot": "auto",
  "ports": {
    "8000/tcp": 8000,
    "16622/tcp": 16622,
    "16623/tcp": 16623,
    "28492/tcp": 28492
  },
  "ingress": false,
  "options": {},
  "schema": {},
  "environment": {
    "COMPANION_CONFIG_BASEDIR": "/data"
  },
  "map": ["data:rw"]
}
