name: "Bitfocus Companion"
description: "Bitfocus Companion voor het aansturen van een Stream Deck via Companion Satellite"
version: "1.0.0"
slug: "bitfocus_companion"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8000]/"
panel_icon: "mdi:remote"
ports:
  8000/tcp: 8000
  16622/tcp: 16622
  16623/tcp: 16623
  28492/tcp: 28492
ports_description:
  8000/tcp: "Web interface"
  16622/tcp: "Satellite API"
  16623/tcp: "WebSocket (Elgato Plugin)"
  28492/tcp: "Additional port"
devices:
  - /dev/bus/usb
privileged:
  - NET_ADMIN
  - DAC_READ_SEARCH
  - SYS_ADMIN
hassio_api: true
hassio_role: default
docker_api: true
