name: "Bitfocus Companion"
description: "Bitfocus Companion voor het aansturen van een Stream Deck via Companion Satellite"
version: "1.0.0"
slug: "bitfocus_companion"
init: true
arch:
  - aarch64
  - amd64
startup: services
ports:
  8000/tcp: 8000
  16622/tcp: 16622
  16623/tcp: 16623
  28492/tcp: 28492
ports_description:
  8000/tcp: "Web interface"
  16622/tcp: "Satellite API"
  16623/tcp: "WebSocket (Elgato Plugin)"
  28492/tcp: "Additional port"
host_network: false
usb: true
devices:
  - /dev/bus/usb
webui: "http://[HOST]:[PORT:8000]/"
ingress: false  # Ingress optie staat op false omdat standalone webui beter werkt voor deze toepassing
ingress_port: 8000
panel_icon: mdi:remote
options:
  config_dir: "/companion"
schema:
  config_dir: "str"
